Minipot: Nomad v1.6.2 -data-dir fix
pizzamig/minipot pull request #3
Opened 2024-04-11 10:44 UTC by Sidicer

Hello.

While trying to test `bsdpot/potman` on my local machine I noticed that with default configuration `nomad` fails to start on `minipot` guest.

When manually running nomad start command from `/usr/local/etc/rc.d/nomad`  we get `-data-dir` is required.

I added the minor fix to this branch

2024-04-11 13:06 UTC, grembo requested changes

2024-04-11 13:06 UTC, grembo commented on bin/minipot-init
>  sysrc consul_enable="YES"
```suggestion
sysrc nomad_args="-config=/usr/local/etc/nomad/minipot-server.hcl -data-dir=/var/tmp/nomad"
[ -n "$netif" ] && sysrc nomad_args+=" -network-interface=$netif"
sysrc consul_enable="YES"
```

2024-04-11 13:06 UTC, grembo commented on bin/minipot-init
> +
```suggestion
```

2024-04-11 13:16 UTC, grembo approved these changes
LGTM

@pizzamig Could you double check? The reason why this was necessary is in: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272162#c7 (my concerns weren't taken into account, so we have to change our startup script). Leaving in nomad_dir is probably a good idea in terms of being robust, in case the script changes again.

2024-05-03 13:57 UTC, grembo commented
@pizzamig ping

2024-05-07 19:18 UTC, pizzamig approved these changes
It looks good to me!

2024-05-08 11:36 UTC, merged